### ISSUE TITLE
Can't Connect to host

### ISSUE THREAD

**Issue by spazman998** [JGolafshan/keno-api#7]
Is this hosted locally somewhere that you scrape or a keno api? Unable to get to api-info-qld.keno.com.au.

HTTPSConnectionPool(host='api-info-qld.keno.com.au', port=443): Max retries exceeded with url: /v2/info/hotCold?jurisdiction=QLD (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000026B52855130>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

**Comment by JGolafshan** [comment]
Hi, Sorry for such a late reply. No, the scaped data is only stored locally when excepting the program.

I am not familiar with the HTTPSConnectionPool method perhaps try adding the "https://" to the host parameter.

Here is the complete URL, https://api-info-qld.keno.com.au/v2/info/hotCold?jurisdiction=QLD.

I will be updating the docs to include API endpoints and updating the pypi package
